name: all-echoes

on:
  push:
  workflow_dispatch:

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
    - run: |
       echo ${{ github.job }}
       echo ${{ github }}
  echo1:
    uses: ./.github/workflows/echo1.yml
  echo2:
    uses: ./.github/workflows/echo2.yml
  echo3:
    uses: ./.github/workflows/echo3.yml
