name: context

on:
  workflow_dispatch:
  issues: [created, edited]
jobs:
  context:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      with:
        script: |
          console.log(context)
