name: issue-labels

on:
  issues:
      types: [labeled]

jobs:
  labeled:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'bug')
    steps:
    - run: |
        echo ${{ toJSON(github.event.issue.labels) }}
