name: issue-labels

on:
  issues:
      types: [labeled]

jobs:
  labeled:
    runs-on: ubuntu-latest
    #if: contains(github.event.issue.labels.*.name, 'bug')
    if: github.event.label.name == 'bug'
    steps:
    - uses: actions/github-script@v6
      with:
        script: |
          console.log(github.event)
        
