name: rate-limit

on:
  workflow_dispatch:

jobs:
  check:
    env:
      GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
    - run: echo $(gh api rate_limit) | jq >> $GITHUB_STEP_SUMMARY
