name: release
on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    environment: production
    if: github.event_name == 'release' && github.event.action == 'created'
    steps:
    - run: echo done
